### ISSUE TITLE
Installeer Composer en NodeJS

### ISSUE THREAD

**Issue by ReneKrewinkel** [lonne-lee/educom-essentials-1725271449#6]
<p>Bestudeer en installeer de volgende modules:&nbsp;</p>
<ul>
<li>Composer: <a href="https://e-learning.educom.nu/algemeen/composer">https://e-learning.educom.nu/algemeen/composer</a></li>
<li>NodeJS: <a href="https://e-learning.educom.nu/algemeen/nodejs">https://e-learning.educom.nu/algemeen/nodejs</a></li>
</ul>

**Comment by lonne-lee** [comment]
Ik krijg beide niet geïnstalleerd
